# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

trigger: 
 branches: 
   include: 
     - main*


pr: 
  branches: 
    include:
     - main
  paths:
    exclude:
    - README.md
resources: 
  repositories: 
    - repository: support-demo
      type: github
      name: support-demo
      ref: ${{ variables['Build.SourceBranchName'] }}
