# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# File: azure-pipelines.yml
trigger:
- main

extends:
  template: simple-param.yml
  parameters:
      yesNo: false # set to a non-boolean value to have the build fail
resources:
  repositories:
    - repository: support-demo
      type: github
      name: support-demo
      endpoint: shmohanty
      ref: ${{ variables['Build.SourceBranchName'] }}

steps:
- checkout: library
- script: echo ./build.sh
- script: echo ./test.sh
