# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

trigger: 
 branches: 
   include: 
     - main*


pr: 
  branches: 
    include:
     - main
  paths:
    exclude:
    - README.md
resources: 
  repositories: 
    - repository: support-demo
      type: github
      name: support-demo
      endpoint: shmohanty
      ref: ${{ variables['Build.SourceBranchName'] }}
stages:
- stage: secure_buildstage
  pool:
    vmImage: windows-latest
  jobs:
  - job: secure_buildjob
    steps:
    - script: echo This happens before code 
      displayName: 'Base: Pre-build'
    - script: echo Building
      displayName: 'Base: Build'
