# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# File: azure-pipelines.yml
trigger:
 branches:
   include:
     - main* 
pr:
  branches:
    include: 
      - main*     

extends:
  template: simple-param.yml
  parameters:
      yesNo: false # set to a non-boolean value to have the build fail
#resources:
 #repositories:
   ## - repository: repro
      #type: git
      ##name: Test Demo/repro
      #ref: ${{ variables['Build.SourceBranch'] }}
      #ref: refs/heads/Kohith

resources:
 repositories:
  - repository: support-demo
    type: github 
    name: shmohanty/support-demo   
    endpoint: shmohanty
    ref: ${{ variables['Build.SourceBranch'] }}      



